
== Bone Surname in Muhlenberg County Kentucky
=== Introduction [muhlenberg]
**In Progress: Edited 1/18/2019 MDB**

One of the inspirations for collating this information is to provide sources lacking in most of the online trees for John Bone (1762 PA - 1842 KY) and his family in various family trees. Also, I wanted provide evidence for the mistakes I believed was present in the majority of online genealogies for John's birth and other family locations and dates.

The date of John Bone's death in Muhlenberg County, Kentucky, has been frequently "misreported" to be 1832. The original error may have started with the incorrect date published in Robert Gehlmann Bone's _History of the Bone Family in America_ in 1972. This mistake has unfortunately been magnified by online family trees copying subjects from one tree to another without confirming dates from more reliable sources. Robert G. Bone offers the following on page 134 in the section on the Thomas Bone (#H line) family and his son John (#H1):

[quote, Robert G. Bone, History of the Bone Family in America]
After living for eighteen years in Wilson County, Tennessee, John took his wife and their three children, in 1801, to Madison County, Kentucky, where they had four more children. The last one, born 1810, died soon after birth and Jane died about the same time. In the following year John married Catherine Adams and moved to Muhlenburg County, Kentucky. They had four children. John applied for a soldier's pension in 1831 and wrote his will on December 21st of that year. Word was received of the approval of his application for a pension in July 1832, the same month in which John died* (*July 30, 1832). ...

There are several statements that conflict with historical records. First, Robert omits a significant portion, about 12 years, of John Bone's stay in Madison County, Kentucky. John Bone, by his own statement in his pension application, states he moved to Madison County, Kentucky, in  1789. John Bone of interest seems to be identifiable in records there by 1795 and the first tax record for any John Bone is found there in 1789.

Secondly, Robert has a death date for John Bone's first wife, Jane Hill Bone, as 1810. She in actuality would have had to die earlier, possibly 1806 with the birth of her last child. John Bone married Catherine Adams in Christian County in 1808, not after 1810. She is present with him at the time they left Madison County in 1810. It appears Catherine's family moved west prior to the marriage, John went there to marry and bring her back to Madison, then John took his family to Muhlenberg County, Kentucky, in 1810. If there was a child born in 1810, it would have been Catherine's child.

Next, that John Bone applied for a pension application in 1831 seems possibly wrong. The act of Congress for this pension was not passed until June 7th 1832. John appears in court to petition for benefits on July 30th 1832. Robert's statement that he died July 30th 1832 must be wrong on that account alone. Further, John Bone wasn't issued a certificate of pension until March 27th 1833 and payment made in arrears to to March 4th 1831. There is correspondence in the secretary of wars office where John's first payment was mistakenly sent to Shelbyville, TN. The certificate was returned and a new certificate issued September 7th 1833 and sent to Greenville, Kentucky. There are twice yearly records of payments sent to John Bone each year until the second half of 1842.

So, it seems impossible that the 1832 death date recorded by Robert G. Bone in his publication, could be correct. There are similar mistakes regarding other family members, so some caution should be used in taking information from Robert's work without some sources to support it.


I have created a similar collection of records for John Bone and associated family members for Madison County, Kentucky.

There is still work to be done with this generation of Bones. Please share any additional information and original sources you might have regarding these. Thanks -
Michael Dean Baker {email}.

=== The Records of Muhlenberg Kentucky
The following records are only part of those available in Mulenberg County. There are many additional tax records that can be added. The records of some of the children and in-laws are also missing currently or not included because they are found in an adjacent county and I am currently limiting the scope of this list.


==== 1811 Muhlenberg County Tax Lists
[%autowidth,options="header"]
|=====
|Name|1st|2nd|3rd|County|Water|Ent|Sur|Pat|WM>21|B>16| B | H
|Bone John|-|-|200|Ditto|Jarrels Creek|Joshua Cates|J Cates|-|1|1|1|-
|=====

---
==== 1812 John Bone deed from Joshua Cates - 200 Acres

.Deed Book 3, Pg. 201-202, 1812-03-04*
This indenture made this fourth day of March in the year of our Lord one thousand eight hundred and twelve between Joshua Cates and Ustatia his wife of the county of Christian and state of Kentucky of the one part and John Bone of Muhlenberg County and state aforesaid of the other part Witnesseth that the said Joshua Cates & Ustatia his wife for and in consideration of the sum of two hundred and fifty dollars to them in hand paid the receipt whereof they do hereby acknowledge they have granted bargained and sold and by these presents do grant bargain and sell unto the said John Bone and his heirs and assigns forever a certain tract or parcel of land containing two hundred acres by survey bearing date the 14^th day of May, 1799 which was granted to said Cates by virtue of a certificate No. 3104 by the Commissioners lying in Muhlenberg on waters of Pond River North of Jarralds Creek and bounded as follows (to wit) Beginning at a stake about ten poles above his improvements thence West two hundred and forty eight poles to a white oak thence South one hundred and thirty poles to a black oak; thence East two hundred and forty eight poles to a beech thence North one hundred and thirty poles to the Beginning with the appurtenances to the only proper use and benefit of him the said John Bone and his heirs forever to have and to hold the said tract of land with all and singular the appurtenances thereunto belonging or in anywise appertaining and the said Joshua Cates and Ustatia his wife for themselves their Heirs etc. doth hereby covenant and agree to and with the said John Bone his Heirs etc. that they the said Joshua and Ustatia his wife will warrant and forever defend the aforesaid tract or parcel of land from the claim or claims of them the said Joshua and Ustatia his wife his Heirs etc. and the said Joshua & Ustatia his wife warrant
[page] 202
and forever defend the aforesaid tract or parcel of land from the claim or claims of them the said Joshua and Ustatia his wife their Heirs etc and from the claim or claims of any person or persons claiming by through from or under them in any manner whatever In testimony whereof we have hereunto set our hands and affixed our seals the day and date above written.
[.float-group]
--
[.right]
Joshua Cates his mark (seal)
Ustatia Cates (seal)
--
Witness
Phillip Ford }
Joseph B. Cates }
Benjn Downs }

Christian County to wit March 5^th 1812.
This Indenture of bargain and sale from Joshua Cates and Ustatia his wife to John Bone was this day acknowledged by the said Joshua Cates & Ustatia his wife to be their and each of their acts and deed hands and seals and the said Ustatia being examined apart from her husband Relinquished her right of Dower to the within conveyed land according to law which is ordered to be certified to the Muhlenberg County Court Clerks Office and there to be admitted to record
Atteste Jno. Clark C.C.C.

Muhlenberg County Sct. Clerks Office March 7^th 1812.
The within indenture of bargain and sale from Joshua Cates & Ustatia his wife to John Bone was produced to me in my office on the day above mentioned which together with the annexed certificate of the Clerk of Christian County is truly recorded in my office
Atteste Chas. F. Wing C.M.C.

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSTN-KS65-6?i=273&cat=116364[View document at FamilySearch.org]

---
==== 1812 Muhlenberg County Tax Lists
The microfilm copy at FamilySearch.org is mostly unreadable.

---
==== 1813 Muhlenberg County Tax Lists

[%autowidth,options="header"]
|=====
|Name|1st|2nd|3rd|County|Water|Ent|Sur|Pat|WM>21|B>16| B | H
|Bone John|-|-|200|Ditto|Jarrels Creek|Josh^a Cates|Jos^a Cates|Josh^a Cates|1|3|9|5
|=====

---
==== 1813 John Bone to Jack Jones - Emancipation

.Deed Bk 4, Pg 6-7, 1813-12-13
[margin] Bone To Jones
This Indenture made this 13^th day of Dec^r 1813 Between John Boan of the Commonwealth of Kentucky and County of Muhlenberg of the one part and Jack Jones a man of Color of the other part Witnesseth that the said John Boan for for divers good causes and considerations and hereunto moveing have this day emansepated and set free the said Jack Jones to enjoy all the Freedom that any person of coler can enjoy in the Commonwealth aforesaid or that can be enjoyed in the United States The said Jack Jones being about Twenty two or three years of age hereby liberating the said Jack from any claim that I myself or my Heirs may have with him in any manner whatever. Witness my hand & seal
John Bone (seal)

[page] 7
Muhlenberg County Sct
December County Court 1813
The within Instrument of writing purporting to be the Freedom of the within named Jack Jones a man of Colour from John Bone was exhibited into Court and acknowledged by the said Bone a party thereto to be his act and Deed whereupon the Same is admitted to and truly Recorded
att Ch^s F Wing CMCC

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSTN-KSFT-Z?i=414&cat=116364[View document at FamilySearch.org]

---
==== 1813 John Bone Circuit Court Order

.Book 2, Pg 415, 1813-12-13
An Instrument of writing purporting to be the Freedom of Jack Jones a man of Colour the property of John Bone Esquire from the said John Bone was Exhibited into court by the said Parties aforesaid and acknowledged by the said Bone a party thereto, to be his act and Deed, which being examined by the court is Ordered to be recorded.

---
==== 1813 John Bone Circuit Court Order

.Book 2, Pg 415, 1813-12-13
Ordered that William Martin John Bone, John Hill and Hutson Martin, (or any three of them being first sworn view and mark out the best and most convenient way for a road to lead from Greenville to David Campbells mill on Jarrels Creek and report thereof as the law directs

---
==== 1813 John Bone Circuit Court Order

.Book 2, Pg 461, 1814-10-10
Ordered that John Bone be and he is hereby exempt in future from paying County levies for an old infirmed Negro woman by the name of Dinah which is Ordered to be certified to the sheriff of this County.

---
==== 1814 Catherine Adams Bone named in fathers will

.Hopkins County Will Book 1, Pgs. 172-174, 1814-10-14
>This Indenture maid this tenth day of October in the year of our Lord one thousand eight hundred and fourteen I James Adams sen^r of Hopkins County ... Item I do give and leve to my daughter *Caty Bone* a negro garl named Luce that she now hath in possession to her and he Heirs ... Dauther Polly Davis ... daughter Jinny ... son Thomas Adams ... son Andrew Adams ... son Wilson Adams ... wife Agnes Adams ... son Wilson ... sons Matthew, Robert, Alexanders Heirs, Jesse & James ... Hopkins Sct February County Court 1815 The foregoing Instrument of writing was produced in Court and proven to be the last will and Testament of James Adams deceased ... "

Some of these names are found in records associated with John Bone in Madison County, Kentucky. The land John Purchased from a Robert Adams in 1795 is likely the same Robert Adams as Catherine's brother Robert Adams. The Adams family arrival to Western Kentucky, would provide an explanation for John Bone temporarily leaving Madison, Kentucky, about 1808 after his first wife, Jane Hill, had died and marrying Catherine Adams. After his second marriage in Christian County, Kentucky, they returned to Madison County through 1810 before returning West and settling in Muhlenberg County. The brother Matthew Adams is likely the Matthew Adams that was bondsman for the marriage of John Bone and Catherine Adams.

---
==== 1815 Muhlenberg County Tax Lists
[%autowidth,options="header"]
|=====
|Name |1st|2nd|3rd|County |Water |Ent |Sur |Pat | a | b | c | d | e | f | g | h | i | j | k | l | m | n | o
|Bone John |- |- |200 |Muhlenberg |Jarrels Creek |J Cates J |J Cates |J Cates |1 |3 |10 |5 |- |- |- |- |- |- |- |- |3 |- | 3300
|=====

---
==== 1816 Muhlenberg County Tax Lists
[%autowidth,options="header"]
|=====
|Name      |1st |2nd |3rd |County |Water |Ent |Sur |Pat |WM >21|B >16| B | H |$acre|total
|Bone John |-   |-   |200 |ditto  |Garrets Creek|Joshua Cates |Same |Same |1 |3 |9 |6 |2 |3100
|=====


---
==== 1816 John Bone to Matthew Adams - Slave Sale

.Deed Book 4, Pg. 271, 1816-10-14
For and in consideration of the sum of One thousand dollars in hand paid the recept whereof is hereby acknowledged I do by these presents bargain and sell unto Matthew Adams of Hopkins County an State of Kentucky a Negro man name^d Jack slave for life and by occupation a shoe & boot maker Which Negro I warrant to be sound and well free from any Hereditary Complaint whatever Unto the said Matthew Adams his Heirs &^c forever free from the Claims or demands of my self my Heir &^c and from the claims or demands of all other persons Whatever Given under my hand & seal this 14^th day of October 1816.
[.float-group]
--
[.right]
John Bone (seal)
Teste Hutson Martin
--
[margin] Ex^d DD M Adams 14^th Oct^r 1816  fee p^d
Muhlenberg County Sct Clerks Office 14^th day of October 1816.
The foregoing Bill of Sale from John Bone to Matthew Adams was proved to be the Act & deed of the said John Bone by oath of Hutson Martin a Witness thereto which is thereupon truly recorded
Att Ch^s F Wing Clk

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSTN-KSF7-C?i=553&cat=116364[View document at FamilySearch.org]

---
==== 1817 Muhlenberg County Tax Lists
[%autowidth,options="header"]
|=====
|Name      |2nd |3rd |County |Water |Ent |Sur |Pat |WM >21|B >16| B | H |total
|Bone John |-  |200 |Same |Jarrels Cr. |J Cates |Same |Same |1 |2 |7 |5 |2450
|=====

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKW-54F7-S?i=455&cat=156780[View document at FamilySearch.org]

---
==== 1818 Muhlenberg County Tax Lists
[%autowidth,options="header"]
|=====
|Name      |2nd |3rd |County |Water |Ent |Sur |Pat |WM >21|B >16| B | H |total
|Bone John |-  |200 |Same |Jarrels Ck |J Cates |Same |Same |1 |2 |7 |6 |2440
|=====

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKW-54J2-V?i=496&cat=156780[View document at FamilySearch.org]

---
==== 1819 Muhlenberg County Tax Lists
[%autowidth,options="header"]
|=====
|Name      |2nd |3rd |County |Water |Ent |Sur |Pat |WM >21|B >16| B | H |total
|Bone James H| - | - | - | - | - | - | - |1 |- |- |1 |150
|Bone John |-  |200 |Do |Jarrels ck |Joshua Bates |Same |Same |1 |- |- |- |-
| Do       |-  |222 1/2|Hopkins |Trade W. |W^m Parsons |Same |Same |- |4 |8 |5 |4305
|=====

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKW-54FN-Z?i=537&cat=156780[View record for James H. Bone at FamilySearch.org]
https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKW-54JL-Q?i=536&cat=156780[View record for John Bone at FamilySearch.org]

---
==== 1820 Muhlenberg County Tax Lists
[%autowidth,options="header"]
|=====
|Name      |2nd |3rd |County |Water |Ent |Sur |Pat |WM >21|B >16| B | H |total
|Bone John |-  |200 |do |Jarrels Ck |J. Cates |Same |Same |- |- |- |- |-
| ditto    |-  |222 1/2|Hopkins |Trade W. |W^m Parsons |Same |Same |1 |4 |8 |5 |4305
|Bone James H| - | - | - | - | - | - | - |1 |- |- |1 |150
|=====

[View record at FamilySearch.org](https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKW-54FL-F?i=572&cat=156780)

---
==== 1820 Muhlenberg County Census
[%autowidth,cols="21",options="header"]
|=====
|  Name
6+|Free White Males
5+|Free White Female
| Ag
4+|Male Slaves
4+|Female Slaves

|   Name    |-10|-16|16 -18|16 -26|-45|> 45|-10|-16|-26|-45|> 45| Ag  |-14|-26|-45|45 >|-14|-26|-45|> 45
|John Bone  |1  |-  |1    |1    |-  |1  |2  |1  |-  |-  |1? |3  |2  |1  |-  |-  |2  |2  |-  |1
|Trifenia Bone|1  |-  |-  |-    |-  |-  |1  |-  |-  |1  |-  |-  |-  |-  |-  |-  |-  |-  |-  |-
|=====

Ag: persons engaged in agriculture

---
==== 1821 Muhlenberg County Tax Lists
[%autowidth,options="header"]
|=====
|Name      |2nd |3rd |County |Water |Ent |Sur |Pat |WM >21|B >16| B | H |total
|Bone John |-  |200 |ditto |Garrels ck |J Cates |Same |Same |1 |4 |8 |5 |2800
|=====

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKW-54FF-3?i=612&cat=156780[View record at FamilySearch.org]

---
==== 1823 Muhlenberg County Tax Lists
[%autowidth,options="header"]
|=====
|Name      |2nd |3rd |County |Water |Ent |Sur |Pat |$Land|WM >21|B >16| B | H |total
|Bone John | -  |200 |   do |Jarrels Ck|J Cates |Same |Same |1200|- |- |- |- |?
| do       | -  | 50 |   do | do       | -      | -   | -   | 100|1 |4 |8 |4 |?
|=====

[View record at FamilySearch.org]()

---
==== 1824 Muhlenberg County Tax Lists
Bone John 200, 50 acres

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKW-54JN-J?i=749&cat=156780[View record at FamilySearch.org]

---
==== 1828 John Bone to Isaac Bard
**1828-08-27**

.Deed Book 7, Pg. 26-27
[margin] Bone to Bard
Know all men by these presents that I John Bone of the County of Muhlenberg and Commonwealth of Kentucky have this day bargained and sold unto Isaac Bard of Muhlenberg County and state of Kentucky one negro woman about twenty five years old named Lucy one negro boy named Ephraim Thornton McLean, about eight years old also one boy named W^m about six years old, and also one little girl named Cardine Meinerva about four years old for said Bard to have and to hold as his property. And I do hereby bind myself my Heirs and assigns &^c to warrant and defend to the Said Bard against the claim or claims of all and every other person or persons whatever - I do further warrant that the said Negroes are sound and healthy and this conveyance and delivery are made in consideration of Five hundred and thirty dollars in commonwealth paper and one hundred and seventy dollars in specie to me this day in hand paid - witness my hand and Seal this 27^th day of August 1828
[.float-group]
--
[.right]
John Bone (seal)
Teste James J Dozeir
--
[page] 27
Commonwealth of Kentucky Muhlenberg County Sct
Clerks Office February 11^th 1829
The within Bill of Sale was acknowledged by John Bone the maker thereof to be his act and deed for the purposes therein contained which is thereupon admitted to and truly recorded
att Ch^s F Wing clk

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSLX-L9QM-W?i=20&cat=116364[View record at FamilySearch.org]

---
==== 1829 John Bone to Nathaniel Green - 55 Acres

.Deed Book 7, Pg. 18-19, 1829-01-26
[margin] Bone To Green
This Indenture made and entered into this 26^th day of January 1829 between John Bone of the County of Muhlenberg and state of Kentucky of the one part and Nathaniel Green of the same County and State of the other part Witnesseth that the said John Bone hath for and in consideration of the sum of Fifty dollars to him in hand paid at or before the ensealing and delivery of these presents granted bargained and sold and by these presents do grant bargain and sell unto the aforesaid Nathaniel Green and his Heirs and assigns forever all that certain tract or parcel of land situate lying and being in the aforesaid county of Muhlenberg and on the waters of Jarralds Creek containing fifty five acres & butted & bounded

[page] 19
as follows to wit Beginning at two sugar trees and white oak said to be corner to Martin Hardins military survey thence with a line thereof due South 70 poles to two persimmons on the bank of Jarralds creek thence up the same N50E 66 poles to a hickory and poplar on the bank of the creek thence N3E 48 poles to three beeches corner to Hutson Martins survey on the bank of the creek thence N 28 W 40 poles to a black Oak thence N 17 W 54 poles to a white oak thence S 37 W 88 poles to a Stake on the military line thence with the same due East to the Beginning with all and singular the appurtinances to the same belonging or in anywise appurtaining to the said Nathaniel Green and his Heirs and assigns forever To Have and To Hold the said tract of land with the appurtinances and privileges to the same belonging, and the said John Bone for himself his Heirs do hereby covenant and agree to and with the Said Nathaniel green his Heirs &^c that he said John Bone will warrant and defend the aforesaid tract or parcel of land from the claim or claims of him the said John Bone and his Heirs &^c and the said John Bone will forever defend the aforesaid tract or parcel of land from the claim or claims of all and every person or persons claiming by or through him or his Heirs in any way whatever
In testimony whereof I have hereunto set my hand and affixed my seal the day & date above written
John Bone (seal)

Commonwealth of Kentucky Muhlenberg County Sct
Clerks Office January 26^th 1829
This Indenture was acknowledged by John Bone the grantor therein to be his act and deed which is thereupon admitted to and truly Recorded
Att Ch^s F Wing clk

[View record at FamilySearch.org](https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSLX-L93B-M?i=15&cat=116364)

---
==== 1830 John Bone Federal Census - Morgan division

[%autowidth,cols="14",options="header"]
|=====
|
13+^|Males

| Name     |-5 |-10|-15|-20|-30|-40|-50|-60|-70|-80|-90|-100|>100
|John Bone | - | - | - | 1 | - | - | - | - | 1 | - | - | - | -
|=====

[%autowidth,cols="14",options="header"]
|=====
|
13+^|Females
| Name     |-5 |-10|-15|-20|-30|-40|-50|-60|-70|-80|-90|-100|>100
|John Bone | - | - | 1 | 1 | 1 | - | - | - | - | - | - | - | -
|=====

Male Slaves: 1 thru 10, 1 thru 24, 1 thru 38,
Female Slaves: 1 thru 10, 1 24-35, 1 36-55
Total persons: 11

---
==== 1831 Muhlenberg County Tax Lists

[%autowidth,options="header"]
|=====
|  Name  |2d |3d | County |Water |Ent |Sur |Pat |$acre |WM>21 |B>16| B | H |$Val
|Bone John|- |200 |Same|Jarrels ck |J. Kates |Same |Same |2 |1 |2 |6 |7 |1975
|=====

---
==== Margaret Bone to Isaac Bard
**1831-11-22**
*Deed Book 7, Pg. 253-254*
Know all men by these presents that I Margaret Bone of the County of Muhlenberg & State of Kentucky hath bargained and sold unto Isaac Bard of the County
[page] 254
of Muhlenberg & State of Kentucky all my Right and Interest & portion in a negro woman named Lucy & her children to wit Thornton, Billy, Caroline which my father sold said Bard & the increase of of [sic] said Lucy since she was Sold & hereafter, for and in consideration of the sum of Seven hundred dollars already paid to me and my father - And & hereby bind my Heirs & assigns &c to warrant and defend said Interest Right & portion in the above named negroes to the said Bard against the claim or claims of all and every other person or persons whatsoever: as witness my hand & seal this 22^nd day of November 1831
[.float-group]
--
[.right]
Margaret Bone (seal)
--
Teste
John Bone
[margin note] Bone to Bard

Commonwealth of Kentucky Muhlenberg County Sct
I Charles F Wing clerk of the county Court for the County aforesaid do certify that the foregoing Instrument of writing purporting to be a Bill of Sale from Margaret Bone to Isaac Bard was this day produced to me in my Office and proved to be the act and deed of the said Margaret Bone by the Oath of John Bone a subscribing witness thereto, which is thereupon truly recorded
Given under my hand this 3^rd day of January 1831
Ch^s F Wing

https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSLX-L935-3?i=145&cat=116364[View record at FamilySearch.org]

---
==== 1831 John Bone Last Will and Testament

.Will Book 3, Pg. 1-3, 1831-12-12
[page] 1
[margin] Bone^s Will
In the name of God Amen.
I John Bone of the county of Muhlenburg and commonwealth of Kentucky, calling to mind the mortality of the body and knowing that it is appointed for all mankind once to die, and being now in my proper mind do make and ordain this my last will and testament, as followeth, to wit.
In the first place, my will is that all my just debts and funeral expences be paid, and being desirous of making as equal a distribution of my estate among my children as I possibly can, to this end I have made an estimate of the property, that I have given to those of my children that are now married, and from that estimate my daughter **Jane Thomas** has received nine hundred and thirty two dollars, My daughter **Betsey Adams**, has received eight hundred and eighty five dollars, my son **Mark Bone** has received four hundred and fifty four dollars, my son **Thomas Bone** has received four hundred and seven dollars, and my daughter **Susan Bone** has received four hundred and sixty nine dollars. I now give and bequeath to my daughter **Peggy Bone** one negro woman named Ann, and her increase to her and her heirs forever. I give and bequeath to my son **John Bone** a negro boy by the name of Alexander to him and his heirs forever. I give & bequeath to my daughter **Agnes Bone** a negro boy by the name of Wilson to her and her heirs forever. I give and bequeath to my daughter **Nancy Bone**, a negro girl by the name of Lucinda with her increase to her and her heirs forever. My will and desire is that my four last mentioned Children being the four youngest continue to live together on the farm that I now resid [sic] on until my youngest Daughter comes of age. and that they Ocupy the farm and tract of Land including it for their support maintinance and to enable them to cultivate the same and for their greater convenience I leave them one yoke of Oxen and Ox cart two horse creatures twoCows & calves six head of sheep two sow & pigs two plows two pair gear two axes one grubing hoe two Weeding hoes one Iron wedge & one log chain four feather beds & furniture one iron pot & hooks and iron kettle one Dutch Oven one flat Iron One Cotton & flax Wheel one Dining Table one cupboard & Cupboard furniture & I would willingly leave my negro man Peter to assist them on the farm but I fear they could not manage him therefore I request that he be hired out yearly and the proceeds of his hire be Applyed to the support & maintinance of my said Children last mentioned until my youngest Child comes of age and should they be Industrious and something to what I leave for their support I wish my Executors to dvide [sic] it between them a pay regard to Merit should one or more of my 4 youngest Chidren [sic] die before the yougest comes of age my desire that their part be equally divided among the survivors of my four youngest Children & should one or more of the negroes die before my youngest comes of age my will is that they made equal with the other Children. And should it appear at any time before my younges [sic] Child comes of age that then living together is implacable my desire is that my Executors sell the [blank space] and other things left for the

[page] 2
support except the Beds & furniture & place my said four Children in the most elegible situation in their power for the good of the Children and apply the proceeds of which and rent of the farm and hire of Peter to their support and maintinance.

My will and desire is after my death that all the residue of my estate except what I have herein particularly mentioned and my aged Negro Woman Dinah be sold on a credit of twelve months and the money placed at interest until my youngest child comes of age then the whole of my estate to be sold specific Legacey excepted & then to be so divided as to make the parts of the four youngest including the Negroes hereby bequeathed them each amounts to four Hundred and fifty Dollars and should there be a remainder after such remainder is to be equally divided among them & my sons Mark & Thomas & my Daughter Susan Bone and should their Shares amount to nine Hundred Dollars each and their still be a surplus that to be equally divided amoungst all my Children to my aged Woman Dinah who has bee a faithful Slave my will & desire is that she may have the privilege of living with either of my Children that she may Choose and the one she makes choice of I request to build her a hen house and suffer her to raise fowls and should the labour of Dinah not be sufficient for her support I request that each of my children contribute toward her support and should they fail to so my willis that she be maintained out of my estate and whence I have sold to Isaac Bard a family of negroes (to wit) Thornton Billy & Caroline and have made the said Bard a bill of sale therefor & some persons having Doubted whether the complete title to the said Negroes can be made by me by said Bill of Sale unless the same be signed by my Son John Bone Agness Bone & Nancy Bone now in order that my contract with said Bard Shall be honestly carried into effect and to that my will & desire is that last mentioned three children execute to the said Bard a Bill of sale conveying all their right of inheritance in and to the said slaves Lucy and the aforesaid Children and the children she has had or may yet have since I sold her and if they or either refuse or fail to execute such bill of sale thin all the estate both real and personal that I have bequeathed to my said three Children (to wit) John Agness and Nancy all who refuse or either who refuse or fail signing said Bill of sale shall be delivered over immediatly by my Executors to Isaac Bard for damages the said Bard may sustain by their or either of their witholding from said Bard their title to said slaves. I constitue and Charles F Wing James H Bishop and Mark Bone Executors of this my last will and testament hereby revoking all by me made either by word or writing and this to be taken for my last will & Testament and none other witness my hand and seal December 12^th 1831.
[.float-group]
--
[.right]
John Bone (seal)
--
Test W Campbell Michael Lovel S M M Wing W.H.C. Wing James Armstrong

[page] 3
Muhlenberg County Sct December County Court 1831
The foregoing instrument of writing purporting to be the last will and testament of John Bone was exhibited into court and proven to be the act & deed of the said John Bone by the oaths of Sam W W Wing, W H C Wing, and James Armstrong subscribing witnesses thereto and thereupon ordered to be recorded
Att Ch F Wing Clk


---
==== 1831 John Bone Circuit Court Order
**1831-12-20**

.Book 4, Pg. 64
An Instrument of writing purporting to be the will of John Bone was exhibited into court & proven by the oaths of James Armstrong William H C Wing & Samuel M Wing & thereupon ordered to Record
Absent James Taggart Esq
Present Charles Tyler Esq

[View record at FamilySearch.org](https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSTL-J4B1?i=257&cat=130855)

---
==== 1832 Pension Application for Revolutionary War Service
**1832-07-30**
Service N.C. Bone, John Number S.14981 carded

[page] 1
Declaration in order to obtain the benefit of the act of Congress passed June 7^th 1832.
State of Kentucky County of Muhlenberg } S.S.
On this 30^th day of July 1832 personally appeared in open Court before the Justices of the Court of Said County now sitting, John Bone, a resident of the County of Muhlenberg and State aforesaid aged sixty nine years, who being first duly Sworn according to law, doth on his oath, make the following declaration, in order to obtain the benefit of the act of Congress passed June 7^th 1832.
That he entered the service of the United States last of June 1780 and served against the Tories on the forks yadkin State of N. Carolina but does not recollect the time he engaged & Served this tour From Gates^s defeat to some time in May 1781 he served in the N.C. militia for three several tours of three months each. The first Tour was under the following officers (To Wit) James Byers Capt. Gilli Nail Lieu^t Rob^t Martin Ensign John Silliman Serg^t John Silliman Jun^r Serg^t William Loughery Serg^t . He served the 2^nd three months in the N.C Militia under Sam^l Reed Cap^n

[page] 2
John Lucky & himself were Serg^ts . names of the other officers of this company not recollected
In this Tour he was engaged in a Skirmish with the Tories at Co? Gen^l Davidson commanded there & was wounded
And in another skermish with the British at Cowan^s ford Catawba River Gen^l Davidson commanded & was killed
The other three months same service he was under Capt Graham & Lieut John Perviance - the other officers of his company not recollected. In this last service had a skirmish with the British on the Reedy fork of Haw River and afterwards was at the Battle of Guilford where Gen^l Greene commanded as major Gen^l Col^s Lackey & Williams.
After the above service he served ten months in N. & S. Carolina and Georgia under Gen^l Sumpter, Wade Hampton Col. W^m Alexander Cap^t Dan^l Carter first Lieut Gorgie Snoddy Second Lieut & was in several skirmishes One at Dorchester and another at M^c Cords ferry on Congerree. He States that he fully completed his Several Terms of service and was

[page] 3
regularly discharged but that he has lost his discharges and has no documentary evidence of his services whatever and that he knows no person now living whose testimony he can procure who can testify as to his services that he was a volunteer from Rowan County N. Carolina
He states that he was born in York County Pensylvania on the 19^th Sept^r 1762. moved to N. Carolina Rowan County 1765 remained there until s^d Sept^r 1783 and in the year 1785 removed to the western Country & settled in East Tennessee where he continued until the the [sic] year 1789 when he removed to Madison County Kentucky & there remained until the year 1810. when he removed to Muhlenberg his present place of REsidence. & He has a record of his age in the family bible.
He hereby relinquishes every claim whatever to a pension or annuity except the present and declared that his name is not on the pension Roll of the agency of any State.
Sworn the & subscribed the day & year aforesaid
John Bone

We Isaac Bard clergyman residing in the County of Muhlenberg and Hugh Bone residing in the County of Hopkins both of the State of Kentucky hereby certify that we are

[page] 4
well acquainted with John Bone who has Subscribed & sworn to the above declaration that we believe him to be Sixty nine years of age that he is reputed & believed in the neighborhood where he resides to have been a soldier of the Revolution and that we concur in that opinion.
sworn to & subscribed the day & year aforesaid
Isaac Bard
Pastor of Greenville & M^t Zion
Hugh Bone

...

---
==== 1833 John Bone mentioned in pension application of Atkinson
In Elisha Atkinson's pension application presented in Muhlenberg County, Kentucky to John Campbell a justice of the peace, Elisha mentions names of persons in the neighborhood who can testify to his character.
>"State the names of persons to whom you are known in your neighborhood and who can testify as to your character for veracity and their belief of your Services as a soldier of the Revolution. Answer: Richard Thompson, William Martin, Hutson Martin, John Bone, Ezekiel Rice."

---
==== 1834 Muhlenberg County Tax Lists

[%autowidth,options="header"]
|=====
|Name | 2 | 3^d |County|Water|Ent|Sur|Pat|$acre|WM>21|B>16| B |Hire| H | C |$total
|John Bone|-|200| ' |Jarralds|J Cates | Do | Do |2.50| 1 | 2 | 5 | - | 6 | 22 |$2612
|=====

Ent: name entered, Sur: name surveyed, Pat: name patented, B: Blacks, H: horses. C: cattle, Hire: slaves hired out

[View record at FamilySearch.org](https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKW-5WLP-Z?i=147&cat=156780)

---
==== 1835 Muhlenberg County Tax Lists

[%autowidth,options="header"]
|=====
|Name|Acre|County|Water|Ent|Sur|Pat|Rate|WM>21|B>16|B|H|C
|Bone John M|-|-|-|-|-|-|-|1|-|-|2|-
|Bone John Sr|200| ''|Jarrels|J Cates|Do|Do|3|1|2|5|5|20
|=====

[View record at FamilySearch.org](https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKW-5WLJ-3?i=172&cat=156780)

---
==== 1841 John Bone to James S. Green
**1841-07-13 Deed 100 acres**
*Deed Book 10, Pg. 245-246*
[margin] Bone To Green
This Indenture made this 13^th day of July in the year of our lord one thousand Eight hundred and forty one, between John Bone of the county of Muhlenberg and State of Kentucky of the one part and James S. Green of the county and State aforesaid of the other part witnesseth that for and in consideration of two hundred dollars to him in hand paid the Receipt where of he doth hereby acknowledged have granted bargained and Sold and do by these presents grant bargain and Sell unto the Said James S. Green a certain tract or parcel of land lying and being in the county aforesaid to him his heirs and assigns forever on Jarolds creek Beginning at his West corner on the bank of Said creek thence North to his North corner thence with his East line So far as to include one hundred acres with appurtenances to the only proper use and benefit of him the Said James S. Green and his heirs forever to Have and To Hold the Said tract of land with all and Singular the appurteances thereunto belonging or in any wise appertaining and the Said John Bone for himself and his heirs &c doth hereby covenant and agree to and with the Said James S. Green his heirs & that he the Said John Bone will warrant and forever defend the aforesaid tract or parcel of land from the claim or claims of him the Said John Bone his heirs &c and the Said John Bone will warrant and forever defend the aforesaid tract or parcel of land from the claim or claims of him the Said John Bone his heirs &c and from the claim or claims of any person or persons claiming by through him or under him in any manner whatever
John Bone

[page] 246
Muhlenberg count Sct
I Charles F Wing clerk of the county court for the county aforesaid certify that the foregoing deed from John Bone to James S. Green was this day produced to me in my office and acknowledged by the Said Bone to be his act & deed which is thereupon admitted to & truly Recorded
Given under my hand 4^th day of August 1841
Chs F Wing

[View record in FamilySearch.org](https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSTF-4S9K-6?i=509&cat=116364)

---
==== 1841 Muhlenberg County Tax Lists

[%autowidth,options="header"]
|=====
|Name|Acres|County|Water|WM>21|B>16| H | C |Ch7-17|Total$
|John Bone|200|''|Jarralds ck|1|2|3|-|-|2120
|=====

WM: white male; B: black; H: horses; C: cattle; Ch: children

[View record at FamilySearch.org]()

---
==== 1842 Jone Bone Circuit Court Orders
**1842-10-31**

*Book 5, Pg. 28*
Octr County Court 1842 (monday 31^st)
...
On the motion of Mark Bone & John Bone who made oath as the law directs certificate is granted them for obtaining letters of Administration on the estate of John Bone deceased who thereupon together with William C. McNary Mosely P Wells & Howard Duvall their security executed Bond in the penalty of $5000 conditioned as the law directs
https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKX-N9P9?i=49&cat=130855[View record at FamilySearch.org]

---
==== 1842 John Bone Circuit Court Orders
**1842-10-31**
*Book 5, Pg. 29*
Ordered that Samuel McWilkins Michael Lovel James Rice & Andrew L Martin be appointed appraisers or any three of them after being Swearn appraise in current money the personal estate & slaves of John Bone deceased & that the Administrators Return an inventory thereof as the law directs
https://www.familysearch.org/ark:/61903/3:1:3Q9M-CSKX-N9P9?i=49&cat=130855[View record at FamilySearch.org]

---
==== 1842 John Bone Inventory of Estate

*Inventory Appraisement & Sale Book Vol. 4, Pg 20-26, 1842-11-15*
Muhlenberg Count Sct
S.M. Wilkins, Michael Lovel, James F? Rice and A.L. Martin, who have been appointed by the Muhlenberg County court to view and appraise the personal Estate of John Bone deceased was all Sworn to view and appraise Such Estate as Shall be produced to them truly justly to the Best of thare Judgment -
Given under my hand November the 15^th 1842.
S.M. Wilkins J.P.

\[page 21]
Inventory and Appriasment, a true and just Inventory and appraisment, of all the personal Estate and negroes of John Bone dec^d which was produced to us By Mark H. Bone and John Bone his Administrators
Notes
One cash note on Fielding Foster baring interest from 29^th February 1839	146.79
one on Mark H. Bone interest from 1^st March 1842	75.00
one on W. P. Hancock interest from 4^th November 1840	6.26
one on John S. Eaves Interest from 25 April 1842	6.00
one on Jn^o B Staples	43.51
one clock	15.00
one cupboard	10.00
one Bedstead	3.00
one Small table	1.01
five chairs	1.50
one looking Glass	.50
2 chairs	.75
1 burreau	3.00
1 bed bedstead and furniture	7.00
 ...

\[page 22]
 ...

\[page 23]
 ...
we do certify that the foregoing Inventory contains all the personal Estate of John Bone deceased which came to Our hands,
Mark H. Bone
John M. Bone
Adminsitrators of John Bone deceased

we do certify that the foregoing appraisment was fully and justly made of the personal property of John Bone deceased which was produced to us by his Administrators to the best of our judgment All of which we respectfully report to the county court of Muhlenberg.
Given under our hands this 15^th day of November 1842.
S. M. Wilkins }
James W? Rice }
A. L. Martin }
Appraisors of Jn^o Bone dec^d }

Muhlenburg County Sct
November County Court 1842
The foregoing Inventory and appraisment bill of the Estate of John Bone dec^d was Exhibited into court which being Examined and approved of is ordered to be recorded
att Chs F Wing clk

https://www.familysearch.org/ark:/61903/3:1:3QS7-89DL-F1YP?i=17&cc=1875188&cat=788661[View record at FamilySearch.org]

[page 24] 24
The Sale Bill of John Bone deceased (property)

[%autowidth]
|=====
|James Green to one clock|5.00
|James Green to one cupboard|6.50
|James Green to one bedstead & bead|.56 1/4
|Daniel Barnes to lot of chairs|1.25
|S.M. Wilkins to one table|.37 1/2
|John Moore to one looking Glass|.18 1/4
|James Green to one bureau|1.37 1/2
|Agness Bone to one bed & Stead|4.00
|Howard Duvall to 1 mowing sythe|2.00
|T.L. Martin to one Sythe & cradle|.18 1/4
|S.M. Wilkins to one lot of iron|43 1/4
|Mark H. Bone to ne lot of augers|.37 1/2
|S.M. Wilkins to 2 chisels & Square|.37 1/2
|S.M. Wilkins to one drawing knife|.56 1/4
|J M Bone to one Side upper leather|.75
|J.M. Bone to one ? Skin|3.25
|B.B. Walker to one calf Skin|.68 1/4
|J. Green to one Side of Soal Leather|.37 1/4
|C.C. Martin to one pair of fire irons|.12 1/2
|L O Dillingham to cotton wheel|.62 1/2
|J. Green to one mans Saddle|.25
|W. Lee to one square table|1.00
|J Matthis to one flax wheel|.37 1/2
|J. Green to one quilting wheel|.16 1/4
|C.C. Martin to one loom|4.25
|J.M. Bone to one check Reel|.75
|A.L. Martin to one Reed|.25
|W Oates to one pair of steelyards|.25
|J. Green to one pair of spoon moles|.12 1/2
|J Green to one flax hackel|2.00
|D. Barnes to one flat iron & hammer|.37 1/2
|D. Barnes to one sifter|.12 1/2
|D. Barnes to one churn|.50
|J.C. Reynolds to one lot of barrels|1.00
|H. Duvall to one half Bushel|.31 1/4
|William Lee to one bucket|.37 1/2
|S.M. Wilkens to one large kettle|2.00
|T.L. Martin to one lot of pots|.16 1/4
|E.T. Williamson to one Skillet & 2 lids|.25
|J. Rice to one lot of lumber|.75
|J. Green to one crosscut Saw|2.00
|J. Moore one bushel flax seed|.37 1/2
|J. Green to one lot of cotton|1.50
|H. Green to one borad ax|1.62 1/2
|=====

[page] 25
...

[page] 26

[%autowidth]
|=====
|W. Green to one Sorrel horse|35.00
|Agness Bone to one gray filly|15.00
|J. Richardson to one Yolk of oxen|20.62 1/2
|V.L. Dillingham to one yoke oxen|10.12 1/2
|V.L. Dillingham to one Bull|3.18 1/4
| " Same to one muy Steer|6.06 1/4
|John Moore to one muy cow|8.12 1/2
|N. Green to one cow|5.00
|R.B. Earle to one cow|5.00
|Agness Bone to one cow|4.00
|J.W. Sherrod to one cow & calf|8.15
|H. Duvall to one yearling|1.43 3/4
|B.B. Walker to one lot of sheep 1^st choice|3.00
|J. Rollen to one lot of sheep 2^nd choice|2.87 1/2
|B.B. Walker to five Sheep|3.00
|J. Matthews to ten head hogs|13.00
|J. Bass to 30 head of hogs supposed|15.00
|V.L. Dillingham to 20 head of geese|3.00
|Moses Rice to one Slate|.12 1/2
|J.M. Dobns to one stack of hay|.87 1/2
|J. Green to one lot of flax|.50
|=====

Mark Bone and John M. Bone Administrators of John Bone deceased

Muhlenberg County Sct
This day Samuel M. Wilkins was Sworn before me the undersigned this 12^th day of November 1842.
John Campbell J.P.

Muhlenberg County Sct November County Court 1842
The foregoing Sale Bill of the Estate of John Bone deceased, was Exhibited into court, which being Examined and approved of is ordered to be recorded
Teste Ch F Wing clk

https://www.familysearch.org/ark:/61903/3:1:3QS7-89DL-F11R?i=19&cc=1875188&cat=788661[View record at FamilySearch.org]

---
==== 1842 John Bone Circuit Court Orders

.Order Book 5, Pg. 36, 1842-11-28
Inventory & apprasement and sale Bill of the estate of John Bone deceased was returned in to court & ordered to be recorded


---
==== Family Information from an 1867 publication
In _Life and Labors of the Late Rev. Robert Donnell, of Alabama, Minister of the Gospel in the Cumberland Presbyterian Church_ by David Lowry, publish 1867 Alton, Illinois by S.V. Crossman, Printer, Third Street.
There is an appendix containing a sketch of the life of the late Hugh Bone, Esq., of Kentucky.

Page 313
[quote, David Lowry]
Hugh Bone was born in the State of Pennsylvania, on the 19th of October, 1764, and was the second son of Thomas Bone. His parentage, on both sides, was Scotch-Irish Presbyterian descent, and united in his great grandfather, John McWilliams, of Scotland ...

Page 313
[quote, David Lowry]
Hugh Bone was removed, while yet a boy, by his parents, to North Carolina, county of Iredell; and there raised and trained to manhood ...

Page 315 - 316
[quote, David Lowry]
In the 27th year of his age, he was united in marriage to Mary Hill ... While their family was small, he removed to Madison county, Kentucky, where he served, as ruling elder, for seven or eight years, under the pastoral charge of Rev. Matthew Housten ... Shortly after Mr. Bone had removed to Tennessee, Housten visited him ...

Page 316
>He witnessed something of the great revival of 1800, before he removed from Kentucky, to Wilson county ...

Page 317
>In the fall of 1802, he removed to Smith's Fork, Wilson county, Tenn. ...

Page 323
>In tthe spring of 1819, Hugh Bone removed, and settled in Hopkins county, Kentucky, which was then a quite newly settled country ...

https://books.google.com/books?id=rVIDAAAAYAAJ&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false[View this book in books.google.com]
